project: purescript-assert-multiple
version: 0.2.0
author: Joel Lefkowitz
verbose_name: PureScript assert multiple
html_title: PureScript assert multiple 
github_url: https://github.com/JoelLefkowitz/purescript-assert-multiple
