collections:
  - common
  - purescript

excludes:
  - .cspell.json
  - README.md
  - bower.json
  - package.json
  - spago.dhall

render_context:
  project:
    name: purescript-assert-multiple
    description: Chain assertions contained in a monad.
    version: 0.2.0
    verbose_name: PureScript Assert Multiple
    repository: https://github.com/JoelLefkowitz/purescript-assert-multiple
    codacy_id: e554a1597f8b40d9b7e54d7923c2049f

  author:
    author: joellefkowitz
    author_email: joellefkowitz@hotmail.com
    verbose_author: Joel Lefkowitz

clear_top_level: true
logical_grouping: true

loader_paths:
  - docs
