severity: low
exclude:
  - message: Codacy project public id
    pattern: e554a1597f8b40d9b7e54d7923c2049f

  - message: Package owner public ssh key
    pattern: public
    paths:
      - purs.json

  - message: Giphy links
    pattern: https://media.giphy.com/media/

  - message: Build output
    paths:
      - output/cache-db.json

  - message: Docs output
    paths:
      - generated-docs

  - message: Old test output
    paths:
      - .nyc_output

  - message: Dependencies
    paths:
      - bower_components
      - node_modules
      - package-lock.json
      - packages.dhall
      - spago.dhall
      - venv
      - yarn-error.log
      - yarn.lock
